var arrayData = [
    { airportCode: 'COR', flightCode: '1500', carousel: '2', id: 0 },
    { airportCode: 'SLA', flightCode: '1456', carousel: '2', id: 0 },
    { airportCode: 'ROS', flightCode: '1674', carousel: '2', id: 0 },
    { airportCode: 'IRJ', flightCode: '1440', carousel: '2', id: 0 },
    { airportCode: 'BRC', flightCode: '1638', carousel: '4', id: 0 },
    { airportCode: 'NQN', flightCode: '1650', carousel: '4', id: 0 },
    { airportCode: 'RSA', flightCode: '1520', carousel: '4', id: 0 },
    { airportCode: 'CRD', flightCode: '1838', carousel: '4', id: 0 },
    { airportCode: 'LIM', flightCode: '1364', carousel: '3', id: 0 },
    { airportCode: 'POA', flightCode: '1232', carousel: '3', id: 0 },
    { airportCode: 'VVI', flightCode: '1368', carousel: '3', id: 0 },
    { airportCode: 'GIG', flightCode: '1260', carousel: '3', id: 0 },

    { airportCode: 'COR', flightCode: '1500', carousel: '2', id: 0 },
    { airportCode: 'SLA', flightCode: '1456', carousel: '2', id: 0 },
    { airportCode: 'ROS', flightCode: '1674', carousel: '2', id: 0 },
    { airportCode: 'IRJ', flightCode: '1440', carousel: '2', id: 0 },
    { airportCode: 'BRC', flightCode: '1638', carousel: '4', id: 0 },
    { airportCode: 'NQN', flightCode: '1650', carousel: '4', id: 0 },
    { airportCode: 'RSA', flightCode: '1520', carousel: '4', id: 0 },
    { airportCode: 'CRD', flightCode: '1838', carousel: '4', id: 0 },
    { airportCode: 'LIM', flightCode: '1364', carousel: '3', id: 0 },
    { airportCode: 'POA', flightCode: '1232', carousel: '3', id: 0 },
    { airportCode: 'VVI', flightCode: '1368', carousel: '3', id: 0 },
    { airportCode: 'GIG', flightCode: '1260', carousel: '3', id: 0 },
    { airportCode: 'COR', flightCode: '1500', carousel: '2', id: 0 },
    { airportCode: 'SLA', flightCode: '1456', carousel: '2', id: 0 },
    { airportCode: 'ROS', flightCode: '1674', carousel: '2', id: 0 },
    { airportCode: 'IRJ', flightCode: '1440', carousel: '2', id: 0 },
    { airportCode: 'BRC', flightCode: '1638', carousel: '4', id: 0 },
    { airportCode: 'NQN', flightCode: '1650', carousel: '4', id: 0 },
    { airportCode: 'RSA', flightCode: '1520', carousel: '4', id: 0 },
    { airportCode: 'CRD', flightCode: '1838', carousel: '4', id: 0 },
    { airportCode: 'LIM', flightCode: '1364', carousel: '3', id: 0 },
    { airportCode: 'POA', flightCode: '1232', carousel: '3', id: 0 },
    { airportCode: 'VVI', flightCode: '1368', carousel: '3', id: 0 },
    { airportCode: 'GIG', flightCode: '1260', carousel: '3', id: 0 },
]

exports.default = arrayData;